version: '3'

services:
  myapp-mysql:
    image: mariadb:10.5.8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=MyAppDb
      - MYSQL_USER=myapp-user
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306


  minio-server:
    image: minio/minio
    command: 'server /data --console-address ":9001"'
    ports:
      - 9000:9000
      - 9001:9001

networks:
  spring-boot-mysql-network:
    driver: bridge
