version: '3'

services:

  myapp-mysql:
    image: mariadb:10.5.8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=MyAppDb
      - MYSQL_USER=myapp-user
      - MYSQL_PASSWORD=password
      - TZ=America/Sao_Paulo
    networks:
      - spring-boot-mysql-network
    ports:
      - 3306:3306

  myapp:
    image: sistemafapi:0.0.7
    restart: on-failure
    depends_on:
      - myapp-mysql
    networks:
      - spring-boot-mysql-network
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://myapp-mysql/MyAppDb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - app-env.origem-permitida=*
      - DATABASE_USER=myapp-user
      - DATABASE_PASSWORD=password

networks:
  spring-boot-mysql-network:
    driver: bridge
