version: '3'

services:
  myapp-mysql:
    image: mariadb:10.5.8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=MyAppDb
      - MYSQL_USER=myapp-user
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306

  myapp-main:
    image: sistemfapi
    restart: on-failure
    depends_on:
      - myapp-mysql
    networks:
      - spring-boot-mysql-network
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=myapp-mysql
      - DATABASE_USER=myapp-user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=MyAppDb
      - DATABASE_PORT=3306
      - Dserver.port=8081

networks:
  spring-boot-mysql-network:
    driver: bridge
