version: '3'

services:

  myapp-mysql:
    image: mariadb:10.5.8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=MyAppDb
      - MYSQL_USER=myapp-user
      - MYSQL_PASSWORD=password
      - TZ=UTC
    networks:
      - spring-boot-mysql-network
    ports:
      - 3306:3306

  myapp:
    image: felipedb91/sistemafapi:0.0.9
    restart: on-failure
    depends_on:
      - myapp-mysql
    networks:
      - spring-boot-mysql-network
    ports:
      - 8080:8080
    environment:
      - spring.profiles.active=oauth-security,int-api
      - spring.datasource.url=jdbc:mysql://myapp-mysql/MyAppDb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - DATABASE_USER=myapp-user
      - DATABASE_PASSWORD=password
      - app.env.apiUrl=http://localhost:8080
      - app.security.jwt.keystore.jksLocation=base64:MIIKmQIBAzCCClIGCSqGSIb3DQEHAaCCCkMEggo/MIIKOzCCBbIGCSqGSIb3DQEHAaCCBaMEggWfMIIFmzCCBZcGCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFFLJYJ2gLoxIHELZWxxdMiZqqqNjAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQV1EFerq8V5N3y1hadXdo1gSCBNBLbFxsTtEIlgb4sJ0p5/Rw1wHfY0BIZWAgndh8Skpatxaj5KbRpErlhD39ZMdk7CHL6J03ADrDf7jBb/G0KkMQ1f2iyUgX5U13ls6T2ZbFR2YCLIDjk1VQzzXIz5ORTSrWb+rB2mdAU1PWZWrhmtx3XUJgpCTEPi7VceecOd353yZQp3T8ymdfEszBbJagcTOTkfXUU8bzXndBBeABY09jaul/nyec76E6+Hc0KOxwsWzH3hHOkRI0jI10omdCvW4PG8oy9ybphZkkEfRdnTl1EwoCFwteqiIqA2SJqrGJNF7EmJcjwtLfLwtTBCQ+YNdZaNPdz24GCEuS9CxAhXFB/OLvDK/skcYZK0BJR57HrzcVkkRRMDr0s6wsicS5MICDmgNmuxGzb27ukpShgfewEWKhXmUFhWYLnWPxjx2RD0eorGW+EUBlUSoh2QyMhLSua8OjL1z6/3qSYXhItn+YhvSQpkNTTzS2qN29l7Sql/E3oOjvle/7zJub8/+GgnQWKHb2MU1LJ5ko5P8ohP+qoKk2JE3Sg/ORNoGk6jC1lOxUvzS53T7YUQFDm9k4cLNsu0niNSmTnxJ10SEwgPHGY8x8hHW6WJrw7E59xL4KmUibXLy6RaB3DHzang8I/BxZ4P0X0HxM0gEzaOCPFsOCy50xI/KA9qgYqFVuR9nfg+RxZSmPuvvsVGOg3zAb61+60337mWqbTXrFlLgE+HqImNeKOU1N5HHpKpDVzlqDOdOPp0sZOl84yre6tkGQPyNPzEADkT8WP2Qti/vYAOhUjPnadHh69nIlARwclR4bcxwE2V2Md+e41oV2gdwzmzNF+Py7VtzgDMu0zK6+nGsbRyRascE1CBayxM76zH+J0Os9o8i8pDGIBSl5FvHXVtoaM3Lr6tUoVIxMw/VkgQCHASX4jtuDF2dRsWo1YeAv6lnPM2IpY8MOpI5knG2Cpte5WlAstensBvnWcwqUL2xV1C0Z2lbOjgzINpnh3qgrbK5sU0OZOmcBwNmAuWxbf0yO5rz7BKr64FKVjSjxO2kqbhLOfjVSQ6cayg73IwoHe4CpCXwBfP0FXRIZKMGsLT6n0mmZMyDqC3pzoNLhqRiZF9LI5YiBNkuoRA/zm675GsyEZDZBmn13xTMCYzU4ySpDGLjvl2o7jmVKasIdNoaCyB+/g/v92onu4njfPeD7VYkT2O/JAoDjQkO76RT+lmxlA266JOVjulTfGlud9HcKFnbV7CKVqgNBjsPl8Vs9f0ihwkZ6xjwfZr9aaX6xOKwN/DXyxh/2f31RKxWq9X9Vwl4EqYBTDJ9hx2c/zE5aODdmacswEDZUD4rVBBCa4oSqHaEPoFugn1h0VHX/wa5xiMY489qbbJ85wKVfNfLMmYOYw8wlI6fOhtS40GaWeMr64NjoK2qsqHHNmYkolzQkSAaBu4xwYOnAbKNILF+tvY0rhExXtbXbVpOtt0dpCQBFgN5ZXERV/79h01Lp5UoRnamZ/oT6uQ0ztT82dd9bS4OPmJG2iu6AbjLg0dZq+VNMfkKGBDSnNI/QrVKUibaD3jT0F+gTzpeSfgJD2EkZbjGOd6YZW3qmAsg+YXrCJM71qVxiexOE1NoH0tFyeU75OAFxcfP+vjBwBn4z5f4vSTFEMB8GCSqGSIb3DQEJFDESHhAAYQBsAGcAYQBmAG8AbwBkMCEGCSqGSIb3DQEJFTEUBBJUaW1lIDE2OTQzODk4NzE5NDgwggSBBgkqhkiG9w0BBwagggRyMIIEbgIBADCCBGcGCSqGSIb3DQEHATBmBgkqhkiG9w0BBQ0wWTA4BgkqhkiG9w0BBQwwKwQUAVap8hzDJloDp4rJ0iE7nlgKdAwCAicQAgEgMAwGCCqGSIb3DQIJBQAwHQYJYIZIAWUDBAEqBBDQeoJFsio/EkX4i3qwsTuTgIID8L1ok1tAlZz9FJ7oMpls0YxtnUO+3C9UCLEWdSwUHmGglOm/ctA4nJnIct95u4aXUz9F17hogzH6V+uujrV+eWFpgjY9MM02WQ1qFG9i8WHH6vbdODnWoecK2PbGRwf9dvK+7xsRwi0iDIlUNfIfA5wlMjI6o9yIA+lMXlmyTYpnTwOfPcOpmZeEzAPipNimbmtJGbTSnIJUamoSbHoxcjwd5gZkE+TZtcMMbUoZbhAYhr95pvHLGFRe79u0QCgRVD/LavjoG5+qkXiwigGheL+giUyjNw1BKo5XRjcA48a1FEbMIHzGR3tD21DayWfwyJWR9vEar+ecncF7f/IksoB0xe6YboNBijy319jO607rV3Dl8F32GOkr9X4IfeZc9xcSAJodKuuEcdF3U1deMvx7O6WjBvFcjiwsXVvJh3NS0Do/RYLfoYDdQuxg4Ga3ZvCzJMZDfnXrlkmWvMA/bNlW9AuPg7qC1tlDg+lj665i/X+kEHMqRkguAcbrglfSlHwZD/B8trOPdPlBdEc6CHFmVzYK9YOwqi3vI3SDcdqaTArWyeYMI1wFVeUvtQKYjB4nR6ozCzWwI5z6RMY966nnfuau/va/+d7lR9ShHeU+eVnVZqFyBA095nfid2z6GvR3rkrlz7tFrr3k4SMKZQCZtaWWhEQQuk+H6R7vKauWHn/ZXtrqqNoBWnitwS6X3IgT9kPKBs+qUJNb+354ujN86Lt9q4K26ujL3Zdmc0iZ9DRSoAbChUgImJfsldP5tC0fbqdyjdWV+dWUkiIHs2YXnMOZNOGRPWuw3TsunucauvnpozzUJta3Hty4YkkVPf3Bj0c1n0lsy1r5wTHJhAqTMQhgXovDVGPYmnNj+sURLwsGCWQrpfeW1jVD0iAeGzPxaw/wUJg65ooXzJNICO0tgTxNGM+W+l651eqJgObQ1yGQ3GFjSZBFkmaEKvD3WKKlg0pByCAxgAwWeKVbeIC8MRVF1za000CHe9N8OnY55RIvUHMrP1eO5PdLsWauhDCBnvxIN4PvvIsrTzdbj8Us8G9z3lDmI2scbIQp1NrJ2hwjN6l+vfxQvUiAXYfGI/WCEoL3UAfxGXmKTQc6a+13PpeqqtQNKzX5qSYW7Mw9dIpu6oqj2C10yXvbVfhejKLllt8WKg09kLOpKLqn3kk8aEtfVPOhj65WAaZt8LC2AYgGLUiR//OIHg/DKnCUp4BsQU0xGK2c+qj7adtx+Mn69lCzNyd8EFyIePL9qceZnrxaaQk6WaWiFs963iicM7lQD5r5vSldH+DLpSWuXgyYUknwefZWydfwWVgMldU78iJi08QP0aKtetigaMuJhjA+MCEwCQYFKw4DAhoFAAQUuDbZnagEDUgG9Q9p3oGbgfL0MwoEFPdYFYmupsUHhnHeVGW28SdbAntHAgMBhqA=
      - app.env.allowOrigins=*
      - app.security.clientName=angular
      - app.security.clientSecret=password
      - spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/oauth2/jwks
      - app.security.jwt.keystore.keypairAlias=algafood
      - app.security.jwt.keystore.password=123456
      - app.security.providerUrl=http://localhost:8080
      - app.security.provideUrl=http://localhost:8080
      - app.security.redirectUris=exp://192.168.0.113:8081
      - app.env.apiIntegrationUrl=http://localhost:8080

networks:
  spring-boot-mysql-network:
    driver: bridge
