create table cidade (
	id BIGINT(20) primary key auto_increment,
	nome varchar(70) not null unique
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


insert into cidade(nome)  values( 'Rio de Janeiro' );
insert into cidade(nome)  values( 'São Gonçalo' );
insert into cidade(nome)  values( 'Duque de Caxias' );
insert into cidade(nome)  values( 'Nova Iguaçu' );
insert into cidade(nome)  values( 'Niterói' );
insert into cidade(nome)  values( 'Campos dos Goytacazes' );
insert into cidade(nome)  values( 'Belford Roxo' );
insert into cidade(nome)  values( 'São João de Meriti' );
insert into cidade(nome)  values( 'Petrópolis' );
insert into cidade(nome)  values( 'Volta Redonda' );
insert into cidade(nome)  values( 'Magé' );
insert into cidade(nome)  values( 'Macaé' );
insert into cidade(nome)  values( 'Itaboraí' );
insert into cidade(nome)  values( 'CaboFrio' );
insert into cidade(nome)  values( 'AngradosReis' );
insert into cidade(nome)  values( 'NovaFriburgo' );
insert into cidade(nome)  values( 'BarraMansa' );
insert into cidade(nome)  values( 'Teresópolis' );
insert into cidade(nome)  values( 'Mesquita' );
insert into cidade(nome)  values( 'Nilópolis' );
insert into cidade(nome)  values( 'Maricá' );
insert into cidade(nome)  values( 'Queimados' );
insert into cidade(nome)  values( 'Rio das Ostras' );
insert into cidade(nome)  values( 'Resende' );
insert into cidade(nome)  values( 'Araruama' );
insert into cidade(nome)  values( 'Itaguaí' );
insert into cidade(nome)  values( 'Japeri' );
insert into cidade(nome)  values( 'Itaperuna' );
insert into cidade(nome)  values( 'São Pedro da Aldeia' );
insert into cidade(nome)  values( 'Barrado Piraí' );
insert into cidade(nome)  values( 'Seropédica' );
insert into cidade(nome)  values( 'Saquarema' );
insert into cidade(nome)  values( 'Três Rios' );
insert into cidade(nome)  values( 'Valença' );
insert into cidade(nome)  values( 'RioBonito' );
insert into cidade(nome)  values( 'Guapimirim' );
insert into cidade(nome)  values( 'Cachoeiras de Macacu' );
insert into cidade(nome)  values( 'Paracambi' );
insert into cidade(nome)  values( 'ParaíbadoSul' );
insert into cidade(nome)  values( 'São Francisco de Itabapoana' );
insert into cidade(nome)  values( 'Santo Antônio de Pádua' );
insert into cidade(nome)  values( 'Mangaratiba' );
insert into cidade(nome)  values( 'Paraty' );
insert into cidade(nome)  values( 'Casimiro de Abreu' );
insert into cidade(nome)  values( 'São Fidélis' );
insert into cidade(nome)  values( 'Bom Jesus do Itabapoana' );
insert into cidade(nome)  values( 'Vassouras' );
insert into cidade(nome)  values( 'São João da Barra' );
insert into cidade(nome)  values( 'Tanguá' );
insert into cidade(nome)  values( 'Armação dos Búzios' );
insert into cidade(nome)  values( 'Itatiaia' );
insert into cidade(nome)  values( 'ArraialdoCabo' );
insert into cidade(nome)  values( 'Piraí' );
insert into cidade(nome)  values( 'Patydo Alferes' );
insert into cidade(nome)  values( 'Miracema' );
insert into cidade(nome)  values( 'BomJardim' );
insert into cidade(nome)  values( 'Iguaba Grande' );
insert into cidade(nome)  values( 'Miguel Pereira' );
insert into cidade(nome)  values( 'Pinheiral' );
insert into cidade(nome)  values( 'Itaocara' );
insert into cidade(nome)  values( 'Quissamã' );
insert into cidade(nome)  values( 'Conceição de Macabu' );
insert into cidade(nome)  values( 'Silva Jardim' );
insert into cidade(nome)  values( 'Cordeiro' );
insert into cidade(nome)  values( 'São José do Vale do Rio Preto' );
insert into cidade(nome)  values( 'Cantagalo' );
insert into cidade(nome)  values( 'PortoReal' );
insert into cidade(nome)  values( 'Carmo' );
insert into cidade(nome)  values( 'Mendes' );
insert into cidade(nome)  values( 'Porciúncula' );
insert into cidade(nome)  values( 'Rio Claro' );
insert into cidade(nome)  values( 'Sapucaia' );
insert into cidade(nome)  values( 'Sumidouro' );
insert into cidade(nome)  values( 'Natividade' );
insert into cidade(nome)  values( 'Carapebus' );
insert into cidade(nome)  values( 'Cambuci' );
insert into cidade(nome)  values( 'Italva' );
insert into cidade(nome)  values( 'Engenheiro Paulo de Frontin' );
insert into cidade(nome)  values( 'Quatis' );
insert into cidade(nome)  values( 'Cardoso Moreira' );
insert into cidade(nome)  values( 'Areal' );
insert into cidade(nome)  values( 'Duas  Barras' );
insert into cidade(nome)  values( 'Aperibé' );
insert into cidade(nome)  values( 'Varre-Sai' );
insert into cidade(nome)  values( 'Trajano de Moraes' );
insert into cidade(nome)  values( 'Santa Maria Madalena' );
insert into cidade(nome)  values( 'São Sebastião do Alto' );
insert into cidade(nome)  values( 'Riodas Flores' );
insert into cidade(nome)  values( 'Comendador Levy Gasparian' );
insert into cidade(nome)  values( 'Laje do Muriaé' );
insert into cidade(nome)  values( 'São José de Ubá' );
insert into cidade(nome)  values( 'Macuco' );
