create table bairro (
	id BIGINT(20) primary key auto_increment,
	nome varchar(70) not null unique,
	codigo_cidade BIGINT(20) not null,
	FOREIGN KEY (codigo_cidade) REFERENCES cidade(id)
 )ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO bairro (`nome`, `codigo_cidade`) VALUES
('SÃO CRISTÓVÃO', 1),
('BENFICA', 1),
( 'CAJU', 1),
( 'CATUMBI', 1),
( 'CENTRO', 1),
( 'CIDADE NOVA', 1),
( 'ESTÁCIO', 1),
( 'FLAMENGO', 1),
( 'GAMBOA', 1),
( 'GLÓRIA', 1),
( 'LAPA', 1),
( 'MANGUEIRA', 1),
( 'PAQUETÁ', 1),
( 'RIO COMPRIDO', 1),
( 'SANTA TERESA', 1),
( 'SANTO CRISTO', 1),
( 'SAÚDE', 1),
( 'VASCO DA GAMA', 1),
( 'BOTAFOGO', 1),
( 'CATETE', 1),
( 'COPACABANA', 1),
( 'COSME VELHO', 1),
( 'GÁVEA', 1),
( 'HUMAITÁ', 1),
( 'IPANEMA', 1),
( 'JARDIM BOTÂNICO', 1),
( 'LAGOA', 1),
( 'LARANJEIRAS', 1),
( 'LEBLON', 1),
( 'LEME', 1),
( 'ROCINHA', 1),
( 'SÃO CONRADO', 1),
( 'URCA', 1),
( 'VIDIGAL', 1),
( 'ANIL', 1),
( 'BARRA DA TIJUCA', 1),
( 'CAMORIM', 1),
( 'CIDADEDEDEUS', 1),
( 'CURICICA', 1),
( 'FREGUESIA DE JACAREPAGUÁ', 1),
( 'GARDÊNIA AZUL', 1),
( 'GRUMARI', 1),
( 'ITANHANGÁ', 1),
( 'JACAREPAGUÁ', 1),
( 'JOÁ', 1),
( 'PRAÇA SECA', 1),
( 'PECHINCHA', 1),
( 'RECREIO DOS BANDEIRANTES', 1),
( 'TANQUE', 1),
( 'TAQUARA', 1),
( 'VARGEM GRANDE', 1),
( 'VARGEM PEQUENA', 1),
( 'VILA VALQUEIRE', 1),
( 'BANGU', 1),
( 'DEODORO', 1),
( 'GERICINÓ', 1),
( 'JARDIM SULACAP', 1),
( 'MAGALHÃES BASTOS', 1),
( 'PADRE MIGUEL', 1),
( 'REALENGO', 1),
( 'SANTÍSSIMO', 1),
( 'SENADOR CAMARÁ', 1),
( 'VILA MILITAR', 1),
( 'BARRA DE GUARATIBA', 1),
( 'CAMPO GRANDE', 1),
( 'COSMOS GUARATIBA', 1),
( 'INHOAÍBA PACIÊNCIA', 1),
( 'PEDRA DE GUARATIBA', 1),
( 'SANTA CRUZ', 1),
( 'SENADOR VASCONCELOS', 1),
( 'SEPETIBA', 1),
( 'ALTO DA BOA VISTA', 1),
( 'ANDARAÍ', 1),
( 'GRAJAÚ', 1),
( 'MARACANÃ', 1),
( 'PRAÇA DA BANDEIRA', 1),
( 'TIJUCA', 1),
( 'VILA ISABEL', 1),
( 'ABOLIÇÃO', 1),
( 'ÁGUASANTA', 1),
( 'CACHAMBI', 1),
( 'DEL CASTILHO', 1),
('ENCANTADO', 1),
( 'ENGENHO DE DENTRO', 1),
( 'ENGENHO NOVO', 1),
( 'HIGIENÓPOLIS', 1),
( 'JACARÉ', 1),
( 'JACAREZINHO', 1),
( 'LINS DE VASCONCELOS', 1),
( 'MANGUINHOS', 1),
( 'MARIA DA GRAÇA', 1),
( 'MÉIER', 1),
( 'PIEDADE', 1),
( 'PILARES', 1),
( 'RIACHUELO', 1),
('ROCHA', 1),
( 'SAMPAIO', 1),
( 'SÃO FRANCISCO XAVIER', 1),
( 'TODOS OS SANTOS', 1),
( 'BONSUCESSO', 1),
( 'CACUIA', 1),
( 'CIDADE UNIVERSITÁRIA', 1),
( 'COCOTÁ', 1),
('FREGUESIA', 1),
( 'GALEÃO', 1),
( 'JARDIM CARIOCA', 1),
( 'JARDIM GUANABARA', 1),
( 'MARÉ', 1),
( 'MONERÓ', 1),
( 'OLARIA', 1),
( 'PITANGUEIRAS', 1),
( 'PORTUGUESA', 1),
( 'PRAIA DA BANDEIRA', 1),
( 'RAMOS', 1),
( 'RIBEIRA', 1),
( 'TAUÁ', 1),
( 'ZUMBI', 1),
( 'ACARI', 1),
( 'ANCHIETA', 1),
( 'BARROS FILHO', 1),
( 'BENTO RIBEIRO', 1),
( 'BRÁSDE PINA', 1),
( 'CAMPINHO', 1),
( 'CAVALCANTI', 1),
( 'CASCADURA', 1),
('COELHONETO', 1),
( 'COLÉGIO', 1),
( 'COMPLEXO DO ALEMÃO', 1),
( 'CORDOVIL', 1),
( 'COSTA BARROS', 1),
( 'ENGENHEIRO LEAL', 1),
( 'ENGENHO DA RAINHA', 1),
( 'GUADALUPE', 1),
( 'HONÓRIO GURGEL', 1),
( 'INHAÚMA', 1),
( 'IRAJÁ', 1),
( 'JARDIM AMÉRICA', 1),
( 'MADUREIRA', 1),
( 'MARECHAL HERMES', 1),
('OSWAL DO CRUZ', 1),
( 'PARADA DE LUCAS', 1),
( 'PARQUE ANCHIETA', 1),
( 'PARQUE COLÚMBIA', 1),
( 'PAVUNA', 1),
( 'PENHA', 1),
( 'PENHA CIRCULAR', 1),
( 'QUINTINO BOCAIUVA', 1),
( 'RICARDO DE ALBUQUERQUE', 1),
( 'ROCHA MIRANDA', 1),
( 'TOMÁS COELHO', 1),
( 'TURIAÇU', 1),
( 'VAZ LOBO', 1),
( 'VICENTE DE CARVALHO', 1),
( 'VIGÁRIO GERAL', 1),
( 'VILA DA PENHA', 1),
( 'VILA KOSMOS', 1),
( 'VISTA ALEGRE', 1);
